[18/Jul/2016 10:17:06] DEBUG [stripe:256] API request to https://api.stripe.com/v1/customers returned (response code, response body) of (200, '{\n  "id": "cus_8qFIyOcNMaWa4x",\n  "object": "customer",\n  "account_balance": 0,\n  "created": 1468837024,\n  "currency": null,\n  "default_source": "card_18YYo8HRSbnb4ulEirg6mOgk",\n  "delinquent": false,\n  "description": "me456@me.com",\n  "discount": null,\n  "email": "me456@me.com",\n  "livemode": false,\n  "metadata": {},\n  "shipping": null,\n  "sources": {\n    "object": "list",\n    "data": [\n      {\n        "id": "card_18YYo8HRSbnb4ulEirg6mOgk",\n        "object": "card",\n        "address_city": null,\n        "address_country": null,\n        "address_line1": null,\n        "address_line1_check": null,\n        "address_line2": null,\n        "address_state": null,\n        "address_zip": null,\n        "address_zip_check": null,\n        "brand": "Visa",\n        "country": "US",\n        "customer": "cus_8qFIyOcNMaWa4x",\n        "cvc_check": "pass",\n        "dynamic_last4": null,\n        "exp_month": 1,\n        "exp_year": 2017,\n        "fingerprint": "FJcN215VFRWzooHH",\n        "funding": "credit",\n        "last4": "4242",\n        "metadata": {},\n        "name": null,\n        "tokenization_method": null\n      }\n    ],\n    "has_more": false,\n    "total_count": 1,\n    "url": "/v1/customers/cus_8qFIyOcNMaWa4x/sources"\n  },\n  "subscriptions": {\n    "object": "list",\n    "data": [],\n    "has_more": false,\n    "total_count": 0,\n    "url": "/v1/customers/cus_8qFIyOcNMaWa4x/subscriptions"\n  }\n}\n')
[18/Jul/2016 10:17:06] INFO [accounts.views:29] customer {
  "account_balance": 0, 
  "created": 1468837024, 
  "currency": null, 
  "default_source": "card_18YYo8HRSbnb4ulEirg6mOgk", 
  "delinquent": false, 
  "description": "me456@me.com", 
  "discount": null, 
  "email": "me456@me.com", 
  "id": "cus_8qFIyOcNMaWa4x", 
  "livemode": false, 
  "metadata": {}, 
  "object": "customer", 
  "shipping": null, 
  "sources": {
    "data": [
      {
        "address_city": null, 
        "address_country": null, 
        "address_line1": null, 
        "address_line1_check": null, 
        "address_line2": null, 
        "address_state": null, 
        "address_zip": null, 
        "address_zip_check": null, 
        "brand": "Visa", 
        "country": "US", 
        "customer": "cus_8qFIyOcNMaWa4x", 
        "cvc_check": "pass", 
        "dynamic_last4": null, 
        "exp_month": 1, 
        "exp_year": 2017, 
        "fingerprint": "FJcN215VFRWzooHH", 
        "funding": "credit", 
        "id": "card_18YYo8HRSbnb4ulEirg6mOgk", 
        "last4": "4242", 
        "metadata": {}, 
        "name": null, 
        "object": "card", 
        "tokenization_method": null
      }
    ], 
    "has_more": false, 
    "object": "list", 
    "total_count": 1, 
    "url": "/v1/customers/cus_8qFIyOcNMaWa4x/sources"
  }, 
  "subscriptions": {
    "data": [], 
    "has_more": false, 
    "object": "list", 
    "total_count": 0, 
    "url": "/v1/customers/cus_8qFIyOcNMaWa4x/subscriptions"
  }
}
[18/Jul/2016 10:17:07] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 10:17:08] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/charges HTTP/1.1" 200 1499
[18/Jul/2016 10:17:08] INFO [stripe:252] POST https://api.stripe.com/v1/charges 200
[18/Jul/2016 10:17:08] DEBUG [stripe:256] API request to https://api.stripe.com/v1/charges returned (response code, response body) of (200, '{\n  "id": "ch_18YYoAHRSbnb4ulEUct0etOQ",\n  "object": "charge",\n  "amount": 100,\n  "amount_refunded": 0,\n  "application_fee": null,\n  "balance_transaction": "txn_18YYoAHRSbnb4ulEb8qHeUG7",\n  "captured": true,\n  "created": 1468837026,\n  "currency": "usd",\n  "customer": "cus_8qFIyOcNMaWa4x",\n  "description": null,\n  "destination": null,\n  "dispute": null,\n  "failure_code": null,\n  "failure_message": null,\n  "fraud_details": {},\n  "invoice": null,\n  "livemode": false,\n  "metadata": {},\n  "order": null,\n  "paid": true,\n  "receipt_email": null,\n  "receipt_number": null,\n  "refunded": false,\n  "refunds": {\n    "object": "list",\n    "data": [],\n    "has_more": false,\n    "total_count": 0,\n    "url": "/v1/charges/ch_18YYoAHRSbnb4ulEUct0etOQ/refunds"\n  },\n  "shipping": null,\n  "source": {\n    "id": "card_18YYo8HRSbnb4ulEirg6mOgk",\n    "object": "card",\n    "address_city": null,\n    "address_country": null,\n    "address_line1": null,\n    "address_line1_check": null,\n    "address_line2": null,\n    "address_state": null,\n    "address_zip": null,\n    "address_zip_check": null,\n    "brand": "Visa",\n    "country": "US",\n    "customer": "cus_8qFIyOcNMaWa4x",\n    "cvc_check": "pass",\n    "dynamic_last4": null,\n    "exp_month": 1,\n    "exp_year": 2017,\n    "fingerprint": "FJcN215VFRWzooHH",\n    "funding": "credit",\n    "last4": "4242",\n    "metadata": {},\n    "name": null,\n    "tokenization_method": null\n  },\n  "source_transfer": null,\n  "statement_descriptor": null,\n  "status": "succeeded"\n}\n')
[18/Jul/2016 10:17:08] INFO [accounts.views:37] charge {
  "amount": 100, 
  "amount_refunded": 0, 
  "application_fee": null, 
  "balance_transaction": "txn_18YYoAHRSbnb4ulEb8qHeUG7", 
  "captured": true, 
  "created": 1468837026, 
  "currency": "usd", 
  "customer": "cus_8qFIyOcNMaWa4x", 
  "description": null, 
  "destination": null, 
  "dispute": null, 
  "failure_code": null, 
  "failure_message": null, 
  "fraud_details": {}, 
  "id": "ch_18YYoAHRSbnb4ulEUct0etOQ", 
  "invoice": null, 
  "livemode": false, 
  "metadata": {}, 
  "object": "charge", 
  "order": null, 
  "paid": true, 
  "receipt_email": null, 
  "receipt_number": null, 
  "refunded": false, 
  "refunds": {
    "data": [], 
    "has_more": false, 
    "object": "list", 
    "total_count": 0, 
    "url": "/v1/charges/ch_18YYoAHRSbnb4ulEUct0etOQ/refunds"
  }, 
  "shipping": null, 
  "source": {
    "address_city": null, 
    "address_country": null, 
    "address_line1": null, 
    "address_line1_check": null, 
    "address_line2": null, 
    "address_state": null, 
    "address_zip": null, 
    "address_zip_check": null, 
    "brand": "Visa", 
    "country": "US", 
    "customer": "cus_8qFIyOcNMaWa4x", 
    "cvc_check": "pass", 
    "dynamic_last4": null, 
    "exp_month": 1, 
    "exp_year": 2017, 
    "fingerprint": "FJcN215VFRWzooHH", 
    "funding": "credit", 
    "id": "card_18YYo8HRSbnb4ulEirg6mOgk", 
    "last4": "4242", 
    "metadata": {}, 
    "name": null, 
    "object": "card", 
    "tokenization_method": null
  }, 
  "source_transfer": null, 
  "statement_descriptor": null, 
  "status": "succeeded"
}
[18/Jul/2016 10:17:08] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 10:17:09] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/charges HTTP/1.1" 200 1499
[18/Jul/2016 10:17:09] INFO [stripe:252] POST https://api.stripe.com/v1/charges 200
[18/Jul/2016 10:17:09] DEBUG [stripe:256] API request to https://api.stripe.com/v1/charges returned (response code, response body) of (200, '{\n  "id": "ch_18YYoBHRSbnb4ulELzidzKTd",\n  "object": "charge",\n  "amount": 200,\n  "amount_refunded": 0,\n  "application_fee": null,\n  "balance_transaction": "txn_18YYoBHRSbnb4ulEK3NHN9ay",\n  "captured": true,\n  "created": 1468837027,\n  "currency": "usd",\n  "customer": "cus_8qFIyOcNMaWa4x",\n  "description": null,\n  "destination": null,\n  "dispute": null,\n  "failure_code": null,\n  "failure_message": null,\n  "fraud_details": {},\n  "invoice": null,\n  "livemode": false,\n  "metadata": {},\n  "order": null,\n  "paid": true,\n  "receipt_email": null,\n  "receipt_number": null,\n  "refunded": false,\n  "refunds": {\n    "object": "list",\n    "data": [],\n    "has_more": false,\n    "total_count": 0,\n    "url": "/v1/charges/ch_18YYoBHRSbnb4ulELzidzKTd/refunds"\n  },\n  "shipping": null,\n  "source": {\n    "id": "card_18YYo8HRSbnb4ulEirg6mOgk",\n    "object": "card",\n    "address_city": null,\n    "address_country": null,\n    "address_line1": null,\n    "address_line1_check": null,\n    "address_line2": null,\n    "address_state": null,\n    "address_zip": null,\n    "address_zip_check": null,\n    "brand": "Visa",\n    "country": "US",\n    "customer": "cus_8qFIyOcNMaWa4x",\n    "cvc_check": "pass",\n    "dynamic_last4": null,\n    "exp_month": 1,\n    "exp_year": 2017,\n    "fingerprint": "FJcN215VFRWzooHH",\n    "funding": "credit",\n    "last4": "4242",\n    "metadata": {},\n    "name": null,\n    "tokenization_method": null\n  },\n  "source_transfer": null,\n  "statement_descriptor": null,\n  "status": "succeeded"\n}\n')
[18/Jul/2016 10:17:09] INFO [accounts.views:45] charge_two {
  "amount": 200, 
  "amount_refunded": 0, 
  "application_fee": null, 
  "balance_transaction": "txn_18YYoBHRSbnb4ulEK3NHN9ay", 
  "captured": true, 
  "created": 1468837027, 
  "currency": "usd", 
  "customer": "cus_8qFIyOcNMaWa4x", 
  "description": null, 
  "destination": null, 
  "dispute": null, 
  "failure_code": null, 
  "failure_message": null, 
  "fraud_details": {}, 
  "id": "ch_18YYoBHRSbnb4ulELzidzKTd", 
  "invoice": null, 
  "livemode": false, 
  "metadata": {}, 
  "object": "charge", 
  "order": null, 
  "paid": true, 
  "receipt_email": null, 
  "receipt_number": null, 
  "refunded": false, 
  "refunds": {
    "data": [], 
    "has_more": false, 
    "object": "list", 
    "total_count": 0, 
    "url": "/v1/charges/ch_18YYoBHRSbnb4ulELzidzKTd/refunds"
  }, 
  "shipping": null, 
  "source": {
    "address_city": null, 
    "address_country": null, 
    "address_line1": null, 
    "address_line1_check": null, 
    "address_line2": null, 
    "address_state": null, 
    "address_zip": null, 
    "address_zip_check": null, 
    "brand": "Visa", 
    "country": "US", 
    "customer": "cus_8qFIyOcNMaWa4x", 
    "cvc_check": "pass", 
    "dynamic_last4": null, 
    "exp_month": 1, 
    "exp_year": 2017, 
    "fingerprint": "FJcN215VFRWzooHH", 
    "funding": "credit", 
    "id": "card_18YYo8HRSbnb4ulEirg6mOgk", 
    "last4": "4242", 
    "metadata": {}, 
    "name": null, 
    "object": "card", 
    "tokenization_method": null
  }, 
  "source_transfer": null, 
  "statement_descriptor": null, 
  "status": "succeeded"
}
[18/Jul/2016 10:17:09] INFO [accounts.views:83] Handling login GET request
[18/Jul/2016 10:23:52] INFO [accounts.views:75] Handling login GET request
[18/Jul/2016 10:23:52] WARNING [py.warnings:89] /Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py:28: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(c)

[18/Jul/2016 10:24:11] INFO [accounts.views:75] Handling login POST request
[18/Jul/2016 10:24:11] INFO [accounts.views:69] Handling profile GET request
[18/Jul/2016 10:24:18] INFO [accounts.views:105] Handling topup GET request
[18/Jul/2016 10:24:18] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 10:24:19] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/charges HTTP/1.1" 200 1498
[18/Jul/2016 10:24:19] INFO [stripe:252] POST https://api.stripe.com/v1/charges 200
[18/Jul/2016 10:24:19] DEBUG [stripe:256] API request to https://api.stripe.com/v1/charges returned (response code, response body) of (200, '{\n  "id": "ch_18YYv7HRSbnb4ulE0ksOpUjZ",\n  "object": "charge",\n  "amount": 99,\n  "amount_refunded": 0,\n  "application_fee": null,\n  "balance_transaction": "txn_18YYv8HRSbnb4ulEYkHgrEXi",\n  "captured": true,\n  "created": 1468837457,\n  "currency": "usd",\n  "customer": "cus_8qFIyOcNMaWa4x",\n  "description": null,\n  "destination": null,\n  "dispute": null,\n  "failure_code": null,\n  "failure_message": null,\n  "fraud_details": {},\n  "invoice": null,\n  "livemode": false,\n  "metadata": {},\n  "order": null,\n  "paid": true,\n  "receipt_email": null,\n  "receipt_number": null,\n  "refunded": false,\n  "refunds": {\n    "object": "list",\n    "data": [],\n    "has_more": false,\n    "total_count": 0,\n    "url": "/v1/charges/ch_18YYv7HRSbnb4ulE0ksOpUjZ/refunds"\n  },\n  "shipping": null,\n  "source": {\n    "id": "card_18YYo8HRSbnb4ulEirg6mOgk",\n    "object": "card",\n    "address_city": null,\n    "address_country": null,\n    "address_line1": null,\n    "address_line1_check": null,\n    "address_line2": null,\n    "address_state": null,\n    "address_zip": null,\n    "address_zip_check": null,\n    "brand": "Visa",\n    "country": "US",\n    "customer": "cus_8qFIyOcNMaWa4x",\n    "cvc_check": "pass",\n    "dynamic_last4": null,\n    "exp_month": 1,\n    "exp_year": 2017,\n    "fingerprint": "FJcN215VFRWzooHH",\n    "funding": "credit",\n    "last4": "4242",\n    "metadata": {},\n    "name": null,\n    "tokenization_method": null\n  },\n  "source_transfer": null,\n  "statement_descriptor": null,\n  "status": "succeeded"\n}\n')
[18/Jul/2016 10:24:19] INFO [accounts.views:113] charge {
  "amount": 99, 
  "amount_refunded": 0, 
  "application_fee": null, 
  "balance_transaction": "txn_18YYv8HRSbnb4ulEYkHgrEXi", 
  "captured": true, 
  "created": 1468837457, 
  "currency": "usd", 
  "customer": "cus_8qFIyOcNMaWa4x", 
  "description": null, 
  "destination": null, 
  "dispute": null, 
  "failure_code": null, 
  "failure_message": null, 
  "fraud_details": {}, 
  "id": "ch_18YYv7HRSbnb4ulE0ksOpUjZ", 
  "invoice": null, 
  "livemode": false, 
  "metadata": {}, 
  "object": "charge", 
  "order": null, 
  "paid": true, 
  "receipt_email": null, 
  "receipt_number": null, 
  "refunded": false, 
  "refunds": {
    "data": [], 
    "has_more": false, 
    "object": "list", 
    "total_count": 0, 
    "url": "/v1/charges/ch_18YYv7HRSbnb4ulE0ksOpUjZ/refunds"
  }, 
  "shipping": null, 
  "source": {
    "address_city": null, 
    "address_country": null, 
    "address_line1": null, 
    "address_line1_check": null, 
    "address_line2": null, 
    "address_state": null, 
    "address_zip": null, 
    "address_zip_check": null, 
    "brand": "Visa", 
    "country": "US", 
    "customer": "cus_8qFIyOcNMaWa4x", 
    "cvc_check": "pass", 
    "dynamic_last4": null, 
    "exp_month": 1, 
    "exp_year": 2017, 
    "fingerprint": "FJcN215VFRWzooHH", 
    "funding": "credit", 
    "id": "card_18YYo8HRSbnb4ulEirg6mOgk", 
    "last4": "4242", 
    "metadata": {}, 
    "name": null, 
    "object": "card", 
    "tokenization_method": null
  }, 
  "source_transfer": null, 
  "statement_descriptor": null, 
  "status": "succeeded"
}
[18/Jul/2016 10:24:19] INFO [accounts.views:69] Handling profile GET request
[18/Jul/2016 10:43:20] INFO [accounts.views:105] Handling topup GET request
[18/Jul/2016 10:43:20] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 10:43:21] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/charges HTTP/1.1" 400 237
[18/Jul/2016 10:43:21] INFO [stripe:252] POST https://api.stripe.com/v1/charges 400
[18/Jul/2016 10:43:21] DEBUG [stripe:256] API request to https://api.stripe.com/v1/charges returned (response code, response body) of (400, '{\n  "error": {\n    "type": "invalid_request_error",\n    "message": "You have passed a blank string for \'customer\'. You should remove the \'customer\' parameter from your request or supply a non-blank value.",\n    "param": "customer"\n  }\n}\n')
[18/Jul/2016 10:43:21] ERROR [django.request:284] Internal Server Error: /topup/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 110, in topup
    customer=request.user.stripe_id
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/resource.py", line 415, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 138, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 270, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 157, in handle_api_error
    rbody, rcode, resp, rheaders)
InvalidRequestError: Request req_8qFjvCMTkGZmue: You have passed a blank string for 'customer'. You should remove the 'customer' parameter from your request or supply a non-blank value.
[18/Jul/2016 10:43:21] ERROR [django.request:284] Internal Server Error: /topup/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 110, in topup
    customer=request.user.stripe_id
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/resource.py", line 415, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 138, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 270, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 157, in handle_api_error
    rbody, rcode, resp, rheaders)
InvalidRequestError: Request req_8qFjvCMTkGZmue: You have passed a blank string for 'customer'. You should remove the 'customer' parameter from your request or supply a non-blank value.
[18/Jul/2016 10:43:40] INFO [accounts.views:75] Handling login GET request
[18/Jul/2016 10:43:52] INFO [accounts.views:75] Handling login POST request
[18/Jul/2016 10:43:53] INFO [accounts.views:69] Handling profile GET request
[18/Jul/2016 10:44:06] INFO [accounts.views:105] Handling topup GET request
[18/Jul/2016 10:44:07] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 10:44:07] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/charges HTTP/1.1" 200 1496
[18/Jul/2016 10:44:07] INFO [stripe:252] POST https://api.stripe.com/v1/charges 200
[18/Jul/2016 10:44:07] DEBUG [stripe:256] API request to https://api.stripe.com/v1/charges returned (response code, response body) of (200, '{\n  "id": "ch_18YZEJHRSbnb4ulEWRbEauuf",\n  "object": "charge",\n  "amount": 99,\n  "amount_refunded": 0,\n  "application_fee": null,\n  "balance_transaction": "txn_18YZEJHRSbnb4ulEfjGw59xg",\n  "captured": true,\n  "created": 1468838647,\n  "currency": "usd",\n  "customer": "cus_8qFIyOcNMaWa4x",\n  "description": null,\n  "destination": null,\n  "dispute": null,\n  "failure_code": null,\n  "failure_message": null,\n  "fraud_details": {},\n  "invoice": null,\n  "livemode": false,\n  "metadata": {},\n  "order": null,\n  "paid": true,\n  "receipt_email": null,\n  "receipt_number": null,\n  "refunded": false,\n  "refunds": {\n    "object": "list",\n    "data": [],\n    "has_more": false,\n    "total_count": 0,\n    "url": "/v1/charges/ch_18YZEJHRSbnb4ulEWRbEauuf/refunds"\n  },\n  "shipping": null,\n  "source": {\n    "id": "card_18YYo8HRSbnb4ulEirg6mOgk",\n    "object": "card",\n    "address_city": null,\n    "address_country": null,\n    "address_line1": null,\n    "address_line1_check": null,\n    "address_line2": null,\n    "address_state": null,\n    "address_zip": null,\n    "address_zip_check": null,\n    "brand": "Visa",\n    "country": "US",\n    "customer": "cus_8qFIyOcNMaWa4x",\n    "cvc_check": null,\n    "dynamic_last4": null,\n    "exp_month": 1,\n    "exp_year": 2017,\n    "fingerprint": "FJcN215VFRWzooHH",\n    "funding": "credit",\n    "last4": "4242",\n    "metadata": {},\n    "name": null,\n    "tokenization_method": null\n  },\n  "source_transfer": null,\n  "statement_descriptor": null,\n  "status": "succeeded"\n}\n')
[18/Jul/2016 10:44:07] INFO [accounts.views:113] charge {
  "amount": 99, 
  "amount_refunded": 0, 
  "application_fee": null, 
  "balance_transaction": "txn_18YZEJHRSbnb4ulEfjGw59xg", 
  "captured": true, 
  "created": 1468838647, 
  "currency": "usd", 
  "customer": "cus_8qFIyOcNMaWa4x", 
  "description": null, 
  "destination": null, 
  "dispute": null, 
  "failure_code": null, 
  "failure_message": null, 
  "fraud_details": {}, 
  "id": "ch_18YZEJHRSbnb4ulEWRbEauuf", 
  "invoice": null, 
  "livemode": false, 
  "metadata": {}, 
  "object": "charge", 
  "order": null, 
  "paid": true, 
  "receipt_email": null, 
  "receipt_number": null, 
  "refunded": false, 
  "refunds": {
    "data": [], 
    "has_more": false, 
    "object": "list", 
    "total_count": 0, 
    "url": "/v1/charges/ch_18YZEJHRSbnb4ulEWRbEauuf/refunds"
  }, 
  "shipping": null, 
  "source": {
    "address_city": null, 
    "address_country": null, 
    "address_line1": null, 
    "address_line1_check": null, 
    "address_line2": null, 
    "address_state": null, 
    "address_zip": null, 
    "address_zip_check": null, 
    "brand": "Visa", 
    "country": "US", 
    "customer": "cus_8qFIyOcNMaWa4x", 
    "cvc_check": null, 
    "dynamic_last4": null, 
    "exp_month": 1, 
    "exp_year": 2017, 
    "fingerprint": "FJcN215VFRWzooHH", 
    "funding": "credit", 
    "id": "card_18YYo8HRSbnb4ulEirg6mOgk", 
    "last4": "4242", 
    "metadata": {}, 
    "name": null, 
    "object": "card", 
    "tokenization_method": null
  }, 
  "source_transfer": null, 
  "statement_descriptor": null, 
  "status": "succeeded"
}
[18/Jul/2016 10:44:07] INFO [accounts.views:69] Handling profile GET request
[18/Jul/2016 11:17:44] INFO [accounts.views:17] Handling register GET request
[18/Jul/2016 11:17:44] WARNING [py.warnings:89] /Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py:28: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(c)

[18/Jul/2016 11:18:11] INFO [accounts.views:17] Handling register POST request
[18/Jul/2016 11:18:11] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 11:18:12] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/customers HTTP/1.1" 400 122
[18/Jul/2016 11:18:12] INFO [stripe:252] POST https://api.stripe.com/v1/customers 400
[18/Jul/2016 11:18:12] DEBUG [stripe:256] API request to https://api.stripe.com/v1/customers returned (response code, response body) of (400, '{\n  "error": {\n    "type": "invalid_request_error",\n    "message": "No such plan: REG_MONTHLY",\n    "param": "plan"\n  }\n}\n')
[18/Jul/2016 11:18:12] ERROR [django.request:284] Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 28, in register
    plan='REG_MONTHLY'
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/resource.py", line 415, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 138, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 270, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 157, in handle_api_error
    rbody, rcode, resp, rheaders)
InvalidRequestError: Request req_8qGHnhZNFX53vM: No such plan: REG_MONTHLY
[18/Jul/2016 11:18:12] ERROR [django.request:284] Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 28, in register
    plan='REG_MONTHLY'
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/resource.py", line 415, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 138, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 270, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/stripe/api_requestor.py", line 157, in handle_api_error
    rbody, rcode, resp, rheaders)
InvalidRequestError: Request req_8qGHnhZNFX53vM: No such plan: REG_MONTHLY
[18/Jul/2016 11:20:37] INFO [accounts.views:17] Handling register GET request
[18/Jul/2016 11:20:53] INFO [accounts.views:17] Handling register POST request
[18/Jul/2016 11:20:54] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 11:20:55] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/customers HTTP/1.1" 200 2436
[18/Jul/2016 11:20:55] INFO [stripe:252] POST https://api.stripe.com/v1/customers 200
[18/Jul/2016 11:20:55] DEBUG [stripe:256] API request to https://api.stripe.com/v1/customers returned (response code, response body) of (200, '{\n  "id": "cus_8qGKCU7qIyNIQm",\n  "object": "customer",\n  "account_balance": 0,\n  "created": 1468840854,\n  "currency": "gbp",\n  "default_source": "card_18YZntHRSbnb4ulEMAHvFT6R",\n  "delinquent": false,\n  "description": "me666@me.com",\n  "discount": null,\n  "email": "me666@me.com",\n  "livemode": false,\n  "metadata": {},\n  "shipping": null,\n  "sources": {\n    "object": "list",\n    "data": [\n      {\n        "id": "card_18YZntHRSbnb4ulEMAHvFT6R",\n        "object": "card",\n        "address_city": null,\n        "address_country": null,\n        "address_line1": null,\n        "address_line1_check": null,\n        "address_line2": null,\n        "address_state": null,\n        "address_zip": null,\n        "address_zip_check": null,\n        "brand": "Visa",\n        "country": "US",\n        "customer": "cus_8qGKCU7qIyNIQm",\n        "cvc_check": "pass",\n        "dynamic_last4": null,\n        "exp_month": 1,\n        "exp_year": 2017,\n        "fingerprint": "FJcN215VFRWzooHH",\n        "funding": "credit",\n        "last4": "4242",\n        "metadata": {},\n        "name": null,\n        "tokenization_method": null\n      }\n    ],\n    "has_more": false,\n    "total_count": 1,\n    "url": "/v1/customers/cus_8qGKCU7qIyNIQm/sources"\n  },\n  "subscriptions": {\n    "object": "list",\n    "data": [\n      {\n        "id": "sub_8qGKzrDLB8DH01",\n        "object": "subscription",\n        "application_fee_percent": null,\n        "cancel_at_period_end": false,\n        "canceled_at": null,\n        "created": 1468840854,\n        "current_period_end": 1471519254,\n        "current_period_start": 1468840854,\n        "customer": "cus_8qGKCU7qIyNIQm",\n        "discount": null,\n        "ended_at": null,\n        "livemode": false,\n        "metadata": {},\n        "plan": {\n          "id": "REG_MONTHLY",\n          "object": "plan",\n          "amount": 999,\n          "created": 1468840831,\n          "currency": "gbp",\n          "interval": "month",\n          "interval_count": 1,\n          "livemode": false,\n          "metadata": {},\n          "name": "Monthly_Sub",\n          "statement_descriptor": "Monthly_Sub",\n          "trial_period_days": null\n        },\n        "quantity": 1,\n        "start": 1468840854,\n        "status": "active",\n        "tax_percent": null,\n        "trial_end": null,\n        "trial_start": null\n      }\n    ],\n    "has_more": false,\n    "total_count": 1,\n    "url": "/v1/customers/cus_8qGKCU7qIyNIQm/subscriptions"\n  }\n}\n')
[18/Jul/2016 11:20:55] INFO [accounts.views:31] customer {
  "account_balance": 0, 
  "created": 1468840854, 
  "currency": "gbp", 
  "default_source": "card_18YZntHRSbnb4ulEMAHvFT6R", 
  "delinquent": false, 
  "description": "me666@me.com", 
  "discount": null, 
  "email": "me666@me.com", 
  "id": "cus_8qGKCU7qIyNIQm", 
  "livemode": false, 
  "metadata": {}, 
  "object": "customer", 
  "shipping": null, 
  "sources": {
    "data": [
      {
        "address_city": null, 
        "address_country": null, 
        "address_line1": null, 
        "address_line1_check": null, 
        "address_line2": null, 
        "address_state": null, 
        "address_zip": null, 
        "address_zip_check": null, 
        "brand": "Visa", 
        "country": "US", 
        "customer": "cus_8qGKCU7qIyNIQm", 
        "cvc_check": "pass", 
        "dynamic_last4": null, 
        "exp_month": 1, 
        "exp_year": 2017, 
        "fingerprint": "FJcN215VFRWzooHH", 
        "funding": "credit", 
        "id": "card_18YZntHRSbnb4ulEMAHvFT6R", 
        "last4": "4242", 
        "metadata": {}, 
        "name": null, 
        "object": "card", 
        "tokenization_method": null
      }
    ], 
    "has_more": false, 
    "object": "list", 
    "total_count": 1, 
    "url": "/v1/customers/cus_8qGKCU7qIyNIQm/sources"
  }, 
  "subscriptions": {
    "data": [
      {
        "application_fee_percent": null, 
        "cancel_at_period_end": false, 
        "canceled_at": null, 
        "created": 1468840854, 
        "current_period_end": 1471519254, 
        "current_period_start": 1468840854, 
        "customer": "cus_8qGKCU7qIyNIQm", 
        "discount": null, 
        "ended_at": null, 
        "id": "sub_8qGKzrDLB8DH01", 
        "livemode": false, 
        "metadata": {}, 
        "object": "subscription", 
        "plan": {
          "amount": 999, 
          "created": 1468840831, 
          "currency": "gbp", 
          "id": "REG_MONTHLY", 
          "interval": "month", 
          "interval_count": 1, 
          "livemode": false, 
          "metadata": {}, 
          "name": "Monthly_Sub", 
          "object": "plan", 
          "statement_descriptor": "Monthly_Sub", 
          "trial_period_days": null
        }, 
        "quantity": 1, 
        "start": 1468840854, 
        "status": "active", 
        "tax_percent": null, 
        "trial_end": null, 
        "trial_start": null
      }
    ], 
    "has_more": false, 
    "object": "list", 
    "total_count": 1, 
    "url": "/v1/customers/cus_8qGKCU7qIyNIQm/subscriptions"
  }
}
[18/Jul/2016 11:20:55] ERROR [django.request:284] Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 37, in register
    user = form.save()
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/forms.py", line 50, in save
    instance.save()
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table accounts_user has no column named subscription_end
[18/Jul/2016 11:20:55] ERROR [django.request:284] Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/views.py", line 37, in register
    user = form.save()
  File "/Users/lukerickard/Dropbox/CodeInstitute3/src/DjangoStripePayments/accounts/forms.py", line 50, in save
    instance.save()
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table accounts_user has no column named subscription_end
[18/Jul/2016 11:22:39] INFO [accounts.views:17] Handling register GET request
[18/Jul/2016 11:22:57] INFO [accounts.views:17] Handling register POST request
[18/Jul/2016 11:23:03] INFO [accounts.views:17] Handling register POST request
[18/Jul/2016 11:23:03] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 11:23:05] DEBUG [requests.packages.urllib3.connectionpool:395] "POST /v1/customers HTTP/1.1" 200 2436
[18/Jul/2016 11:23:05] INFO [stripe:252] POST https://api.stripe.com/v1/customers 200
[18/Jul/2016 11:23:05] DEBUG [stripe:256] API request to https://api.stripe.com/v1/customers returned (response code, response body) of (200, '{\n  "id": "cus_8qGMLBLZUQnkXk",\n  "object": "customer",\n  "account_balance": 0,\n  "created": 1468840984,\n  "currency": "gbp",\n  "default_source": "card_18YZpzHRSbnb4ulEmipgvq5O",\n  "delinquent": false,\n  "description": "me777@me.com",\n  "discount": null,\n  "email": "me777@me.com",\n  "livemode": false,\n  "metadata": {},\n  "shipping": null,\n  "sources": {\n    "object": "list",\n    "data": [\n      {\n        "id": "card_18YZpzHRSbnb4ulEmipgvq5O",\n        "object": "card",\n        "address_city": null,\n        "address_country": null,\n        "address_line1": null,\n        "address_line1_check": null,\n        "address_line2": null,\n        "address_state": null,\n        "address_zip": null,\n        "address_zip_check": null,\n        "brand": "Visa",\n        "country": "US",\n        "customer": "cus_8qGMLBLZUQnkXk",\n        "cvc_check": "pass",\n        "dynamic_last4": null,\n        "exp_month": 1,\n        "exp_year": 2017,\n        "fingerprint": "FJcN215VFRWzooHH",\n        "funding": "credit",\n        "last4": "4242",\n        "metadata": {},\n        "name": null,\n        "tokenization_method": null\n      }\n    ],\n    "has_more": false,\n    "total_count": 1,\n    "url": "/v1/customers/cus_8qGMLBLZUQnkXk/sources"\n  },\n  "subscriptions": {\n    "object": "list",\n    "data": [\n      {\n        "id": "sub_8qGMyow280RTut",\n        "object": "subscription",\n        "application_fee_percent": null,\n        "cancel_at_period_end": false,\n        "canceled_at": null,\n        "created": 1468840984,\n        "current_period_end": 1471519384,\n        "current_period_start": 1468840984,\n        "customer": "cus_8qGMLBLZUQnkXk",\n        "discount": null,\n        "ended_at": null,\n        "livemode": false,\n        "metadata": {},\n        "plan": {\n          "id": "REG_MONTHLY",\n          "object": "plan",\n          "amount": 999,\n          "created": 1468840831,\n          "currency": "gbp",\n          "interval": "month",\n          "interval_count": 1,\n          "livemode": false,\n          "metadata": {},\n          "name": "Monthly_Sub",\n          "statement_descriptor": "Monthly_Sub",\n          "trial_period_days": null\n        },\n        "quantity": 1,\n        "start": 1468840984,\n        "status": "active",\n        "tax_percent": null,\n        "trial_end": null,\n        "trial_start": null\n      }\n    ],\n    "has_more": false,\n    "total_count": 1,\n    "url": "/v1/customers/cus_8qGMLBLZUQnkXk/subscriptions"\n  }\n}\n')
[18/Jul/2016 11:23:05] INFO [accounts.views:31] customer {
  "account_balance": 0, 
  "created": 1468840984, 
  "currency": "gbp", 
  "default_source": "card_18YZpzHRSbnb4ulEmipgvq5O", 
  "delinquent": false, 
  "description": "me777@me.com", 
  "discount": null, 
  "email": "me777@me.com", 
  "id": "cus_8qGMLBLZUQnkXk", 
  "livemode": false, 
  "metadata": {}, 
  "object": "customer", 
  "shipping": null, 
  "sources": {
    "data": [
      {
        "address_city": null, 
        "address_country": null, 
        "address_line1": null, 
        "address_line1_check": null, 
        "address_line2": null, 
        "address_state": null, 
        "address_zip": null, 
        "address_zip_check": null, 
        "brand": "Visa", 
        "country": "US", 
        "customer": "cus_8qGMLBLZUQnkXk", 
        "cvc_check": "pass", 
        "dynamic_last4": null, 
        "exp_month": 1, 
        "exp_year": 2017, 
        "fingerprint": "FJcN215VFRWzooHH", 
        "funding": "credit", 
        "id": "card_18YZpzHRSbnb4ulEmipgvq5O", 
        "last4": "4242", 
        "metadata": {}, 
        "name": null, 
        "object": "card", 
        "tokenization_method": null
      }
    ], 
    "has_more": false, 
    "object": "list", 
    "total_count": 1, 
    "url": "/v1/customers/cus_8qGMLBLZUQnkXk/sources"
  }, 
  "subscriptions": {
    "data": [
      {
        "application_fee_percent": null, 
        "cancel_at_period_end": false, 
        "canceled_at": null, 
        "created": 1468840984, 
        "current_period_end": 1471519384, 
        "current_period_start": 1468840984, 
        "customer": "cus_8qGMLBLZUQnkXk", 
        "discount": null, 
        "ended_at": null, 
        "id": "sub_8qGMyow280RTut", 
        "livemode": false, 
        "metadata": {}, 
        "object": "subscription", 
        "plan": {
          "amount": 999, 
          "created": 1468840831, 
          "currency": "gbp", 
          "id": "REG_MONTHLY", 
          "interval": "month", 
          "interval_count": 1, 
          "livemode": false, 
          "metadata": {}, 
          "name": "Monthly_Sub", 
          "object": "plan", 
          "statement_descriptor": "Monthly_Sub", 
          "trial_period_days": null
        }, 
        "quantity": 1, 
        "start": 1468840984, 
        "status": "active", 
        "tax_percent": null, 
        "trial_end": null, 
        "trial_start": null
      }
    ], 
    "has_more": false, 
    "object": "list", 
    "total_count": 1, 
    "url": "/v1/customers/cus_8qGMLBLZUQnkXk/subscriptions"
  }
}
[18/Jul/2016 11:23:05] INFO [accounts.views:65] Handling profile GET request
[18/Jul/2016 11:31:45] INFO [accounts.views:71] Handling login GET request
[18/Jul/2016 11:31:45] WARNING [py.warnings:89] /Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py:28: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(c)

[18/Jul/2016 11:32:03] INFO [accounts.views:71] Handling login POST request
[18/Jul/2016 11:32:03] INFO [accounts.views:65] Handling profile GET request
[18/Jul/2016 11:32:19] WARNING [django.request:182] Not Found: /cancel_subscription
[18/Jul/2016 11:32:19] WARNING [django.request:182] Not Found: /cancel_subscription
[18/Jul/2016 11:34:56] WARNING [django.request:182] Not Found: /cancel_subscription
[18/Jul/2016 11:34:56] WARNING [django.request:182] Not Found: /cancel_subscription
[18/Jul/2016 11:34:58] INFO [accounts.views:65] Handling profile GET request
[18/Jul/2016 11:35:00] INFO [accounts.views:71] Handling login GET request
[18/Jul/2016 11:35:00] WARNING [py.warnings:89] /Users/lukerickard/Dropbox/CodeInstitute3/Virtual_Envs/django_default/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py:28: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(c)

[18/Jul/2016 11:35:10] INFO [accounts.views:71] Handling login POST request
[18/Jul/2016 11:35:10] INFO [accounts.views:65] Handling profile GET request
[18/Jul/2016 11:35:24] INFO [accounts.views:116] Handling cancel_subscription GET request
[18/Jul/2016 11:35:25] INFO [requests.packages.urllib3.connectionpool:788] Starting new HTTPS connection (1): api.stripe.com
[18/Jul/2016 11:35:26] DEBUG [requests.packages.urllib3.connectionpool:395] "GET /v1/customers/cus_8qGMLBLZUQnkXk HTTP/1.1" 200 2436
[18/Jul/2016 11:35:26] INFO [stripe:252] GET https://api.stripe.com/v1/customers/cus_8qGMLBLZUQnkXk 200
